service: lambda-bot

provider:
  name: aws
  runtime: nodejs6.10

#  stage: dev
  region: eu-central-1

  environment:
    CLIENT_ID: ${file(local.yml):slack.clientId}
    CLIENT_SECRET: ${file(local.yml):slack.clientSecret}
    VERIFICATION_TOKEN: ${file(local.yml):slack.verificationToken}

functions:
  event:
    handler: handler.event
    events:
      - http: POST event
